### ISSUE TITLE
Trying to use a file instead of block device

### ISSUE THREAD

**Issue by ser** [debops/ansible-cryptsetup#7]
Hi,
on some servers it might be necessary to have file-based luks device, instead of ready-to-use block device.

It seems that debops-cryptsetup is not ready for that, when i tried to build setup on filename, first glitch happens during checking procedure, it takes several minutes :)

"TASK: debops.cryptsetup : Check if ciphertext block device exists ----- 227.70s"

**Comment by ypid** [comment]
You can do that by creating a file and mapping it as block device using `losetup`. This role also does not support lvm and stuff like this. I think it is best to use a separate role for that. If you find one feel free to open a PR and add a reference to the role.

**Comment by ypid** [comment]
@ser I added and tested support for using regular files. You can give it a try when you want: https://github.com/debops/ansible-cryptsetup/pull/21 Also check the docs in that PR. I tried my best to write some good docs.
